---

#it would be nice if we could just gather facts about one pacakge...
  - name: Gather pacakge facts
    package_facts:
      manager: "auto"

  - name: import HP gpg key
    apt_key: 
      state: present
      id: FADD8D64B1275EA3
      url: https://downloads.linux.hpe.com/SDR/repo/mcp/GPG-KEY-mcp

# remove first, then add. This ensures that if apt-transport-https is installed later we end up in a consistant state with a working cache. 
# Includes support for removing the apt-transport-https package because why not...

  - name: remove HP MCP repo with HTTP transport
    apt_repository:
      repo: "deb http://downloads.linux.hpe.com/SDR/repo/mcp {{hpmcp_distro_source | default(ansible_lsb.codename)}}/{{hpmcp_distro_version | default('current')}} non-free"
      state: absent
      filename: HP-MCP-HTTP
      update_cache: no
    when: packages['apt-transport-https'] is defined
    
  - name: remove HP MCP repo with HTTPS transport
    apt_repository:
      repo: "deb https://downloads.linux.hpe.com/SDR/repo/mcp {{hpmcp_distro_source | default(ansible_lsb.codename)}}/{{hpmcp_distro_version | default('current')}} non-free"
      state: absent
      filename: HP-MCP-HTTPS
      update_cache: no
    when: packages['apt-transport-https'] is not defined

  - name: add HP MCP repo with HTTP transport
    apt_repository:
      repo: "deb http://downloads.linux.hpe.com/SDR/repo/mcp {{hpmcp_distro_source | default(ansible_lsb.codename)}}/{{hpmcp_distro_version | default('current')}} non-free"
      state: present
      filename: HP-MCP-HTTP
      update_cache: yes
    when: packages['apt-transport-https'] is not defined
    
  - name: add HP MCP repo with HTTPS transport
    apt_repository:
      repo: "deb https://downloads.linux.hpe.com/SDR/repo/mcp {{hpmcp_distro_source | default(ansible_lsb.codename)}}/{{hpmcp_distro_version | default('current')}} non-free"
      state: present
      filename: HP-MCP-HTTPS
      update_cache: yes
    when: packages['apt-transport-https'] is defined


  - name: install hpssacli (new hpacucli)
    apt: pkg={{item}} state=installed
    with_items: "{{ hpspp_software }}"
    when: hpspp_software.0 != ""

  - name: symlink hpacucli to hpssacli (so scripts work..)
    file: src=/usr/sbin/hpssacli dest=/usr/sbin/hpacucli owner=root group=root state=link

  - name: enable hp-health on boot
    service: name=hp-health enabled=yes state=started
